### ISSUE TITLE
Error created after update...

### ISSUE THREAD

**Issue by fssem1** [commfish/BTSPAS_Taku_sockeye#2]
https://github.com/commfish/BTSPAS_Taku_sockeye/blob/92fdbe2370c7deb642314f1c196292e285e9311c/code/inseason_analysis.R#L125

"Starting to fit year  2018 
Directory name is  Taku-FW-Inseason-W23-W28--2018 
***** ERROR ***** Non-zero recoveries and u2 not available at end of experiment??? 
 Check above matrix"

Received the same error when I added:
fit.BTSPAS(fw.data,prefix=fw.prefix, add.ones.at.start=TRUE)

**Comment by cschwarz-stat-sfu-ca** [comment]
Fixed. Uploaded new version of BTSPAS (2019-04-29) to GitHub.
