### ISSUE TITLE
Questions for Carl on BTSPAS inseason estimates

### ISSUE THREAD

**Issue by fssem1** [commfish/BTSPAS_Taku_sockeye#3]
1) The commercial catch data from DFO **_should_** include commercial catch including recoveries of tagged fish.
2) I changed the inseason analysis folders to be FullWeek instead of FW and Half Week instead of HW.
3) Inseason, should fit.BTSPAS(fw.data,prefix=fw.prefix, add.ones.at.start=FALSE). Then, if the estimate does not converge, should this be changed to "add.ones.at.start=TRUE." Or what is a clear statement we can put in the Rmarkdown manual for inseason estimates? 
For example. "If the Canadian commercial sockeye fishery does not commence until 2 or more weeks after sockeye are tagged in the fishwheels, then the "add.ones.at.start=TRUE" hack should be implemented inseason. If the 'hack' is implemented in the first weeks of estimates, it should be used the entire season (along with postseason).
4) Is it correct that the inseason estimates are **_not_** expanded by runtiming and this needs to be done manually?
5) The weekly inseason estimate should be the median (50%) estimate from the file/folder 'Taku-FullWeek-Inseason-W*xx*-W*xx*-fallback--2019' output to the file 'Taku-Inseason-W*xx*-W*xx*--Inseason-run.siz.csv.'

**Comment by cschwarz-stat-sfu-ca** [comment]
I updated the manual and slight changes to the code.

**Comment by fssem1** [comment]
1. The commercial catch data from DFO should include commercial catch including recoveries of tagged fish. TRUE
2. Inseason, should fit.BTSPAS(fw.data,prefix=fw.prefix, add.ones.at.start=FALSE). Then, if the estimate does not converge, should this be changed to "add.ones.at.start=TRUE." Or what is a clear statement we can put in the Rmarkdown manual for inseason estimates.  For example. "If the Canadian commercial sockeye fishery does not commence until 2 or more weeks after sockeye are tagged in the fishwheels, then the "add.ones.at.start=TRUE" hack should be implemented inseason. If the 'hack' is implemented in the first weeks of estimates, it should be used the entire season (along with postseason). ADDED to MANUAL
3. Is it correct that the inseason estimates are not expanded by runtiming and this needs to be done manually? CORRECT
4. The weekly inseason estimate should be the median (50%) estimate from the file/folder 'Taku-FullWeek-Inseason-Wxx-Wxx-fallback--2019' output to the file 'Taku-Inseason-Wxx-Wxx--Inseason-run.siz.csv.' THIS SHOULD BE MEAN NOT MEDIAN. UPDATED IN MANUAL.

**Comment by fssem1** [comment]
As to the dropout rate, inseason for 2019 the dropout rate will be:

Dropout rate
Model the year-to-year variation in drop out (including sampling uncertainty) as binomial with n = 50 and
x = 11 which gives mean pdropout = 0.22 with a standard deviation of 0.05938262.

For historical purpose (GP’s work on reconstructing past estimates), the agreed upon dropout rate is n=52 and x=13. So it works out well that this is an input into the function.
